session_name: base
data_directory: extra/data
data_type: CA_MSA
log_directory: extra/log_dir
load_training_data: true
load_test_data: false
load_validation_data: true
n_training_examples: 7000
n_test_examples:
n_validation_examples:
test_file_name: test.csv
is_data_preprocessed: false
data_separator: '|'
diacritics_separator: '*'
text_encoder: ArabicEncoderWithStartSymbol
text_cleaner: valid_arabic_cleaners
max_len: 600
max_steps: 2_0_0_0_0
learning_rate: 0.001
batch_size: 32
adam_beta1: 0.9
adam_beta2: 0.999
use_decay: true
weight_decay: 0.0
embedding_dim: 256
use_prenet: false
prenet_sizes: [512, 256]
cbhg_projections: [128, 256]
cbhg_filters: 16
cbhg_gru_units: 256
post_cbhg_layers_units: [256, 256]
post_cbhg_use_batch_norm: true
use_mixed_precision: false
optimizer_type: Adam
device: cuda
evaluate_frequency: 5000
evaluate_with_error_rates_frequency: 5000
n_predicted_text_tensorboard: 10
model_save_frequency: 5000
train_plotting_frequency: 50000000
n_steps_avg_losses: [100, 500, 1_000, 5_000] # command line display of average loss values for the last n steps
error_rates_n_batches: 10000
test_model_path:
train_resume_model_path:
len_input_symbols: 44
len_target_symbols: 17
optimizer: Adam
git_hash: a71b578
