# Generated by Django 3.1.5 on 2021-07-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw', models.CharField(max_length=400)),
                ('diacritized', models.CharField(max_length=400, null=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('date_diacritized', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
