# Generated by Django 3.1.5 on 2021-07-16 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('API', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student'),
        ),
        migrations.AddField(
            model_name='sentence',
            name='diacritizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.teacher'),
        ),
    ]
