# Generated by Django 3.1.5 on 2021-07-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20210531_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='date_diacritized',
            field=models.DateTimeField(null=True),
        ),
    ]
