# Generated by Django 3.1.5 on 2021-07-09 13:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_sentence_date_diacritized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='date_diacritized',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
